import type { Metadata } from "next";

import Sidebar from "../../components/layouts/Sidebar";
import Navbar from "../../components/layouts/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <main className="w-full">
        <Navbar />
        {children}
      </main>
    </div>
  );
}
